package com.chunmi.testcase.mapper;

import com.chunmi.testcase.model.po.CaseDetail;

public interface CaseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_casedetail
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_casedetail
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insert(CaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_casedetail
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insertSelective(CaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_casedetail
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    CaseDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_casedetail
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(CaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_casedetail
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKey(CaseDetail record);
}