package com.chunmi.testcase.mapper;

import java.util.List;

import com.chunmi.testcase.mapper.basedap.IBaseMapperDao;
import org.apache.ibatis.annotations.Param;

import com.chunmi.testcase.model.po.OperationLog;
import com.chunmi.testcase.model.po.Users;
import com.chunmi.testcase.utils.PageRequest;

public interface OperationLogMapper extends IBaseMapperDao<OperationLog,Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_operation_log
     *
     * @mbg.generated Wed May 23 13:39:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_operation_log
     *
     * @mbg.generated Wed May 23 13:39:52 CST 2018
     */
    int insert(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_operation_log
     *
     * @mbg.generated Wed May 23 13:39:52 CST 2018
     */
    int insertSelective(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_operation_log
     *
     * @mbg.generated Wed May 23 13:39:52 CST 2018
     */
    OperationLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_operation_log
     *
     * @mbg.generated Wed May 23 13:39:52 CST 2018
     */
    int updateByPrimaryKeySelective(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_operation_log
     *
     * @mbg.generated Wed May 23 13:39:52 CST 2018
     */
    int updateByPrimaryKey(OperationLog record);

	Long selectOperationLogsCountsByCondition(@Param("users")Users user);

	List<OperationLog> selectOperationLogListByCondition(@Param("users")Users user, @Param("pageRequest")PageRequest pageRequest);

	Integer delOperationLog(@Param("operationLog")OperationLog operationLog);

	OperationLog selectOperationLogDetailById(@Param("id")Long id);
}