package com.chunmi.testcase.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chunmi.testcase.model.po.ProjectModule;
import com.chunmi.testcase.utils.PageRequest;

public interface ProjectModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Wed Apr 04 10:20:05 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Wed Apr 04 10:20:05 CST 2018
     */
    int insert(ProjectModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Wed Apr 04 10:20:05 CST 2018
     */
    int insertSelective(ProjectModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Wed Apr 04 10:20:05 CST 2018
     */
    ProjectModule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Wed Apr 04 10:20:05 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Wed Apr 04 10:20:05 CST 2018
     */
    int updateByPrimaryKey(ProjectModule record);

	Integer selectModuleCountsByCondition(@Param("module")ProjectModule projectModule);

	List<ProjectModule> selectModuleListByCondition(@Param("pageRequest")PageRequest pageRequest, @Param("module")ProjectModule projectModule);

	ProjectModule selectModuleByProjectIdAndModuleName(@Param("module")ProjectModule projectModule);

	Integer delModule(@Param("module")ProjectModule projectModule);
}