package com.chunmi.testcase.mapper;

import com.chunmi.testcase.model.po.ProjectModule;

public interface ProjectModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insert(ProjectModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insertSelective(ProjectModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    ProjectModule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_module
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKey(ProjectModule record);
}