package com.chunmi.testcase.mapper;

import com.chunmi.testcase.model.po.ProjectVersion;

public interface ProjectVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_version
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_version
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insert(ProjectVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_version
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insertSelective(ProjectVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_version
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    ProjectVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_version
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_version
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKey(ProjectVersion record);
}