package com.chunmi.testcase.mapper;

import java.util.List;

import com.chunmi.testcase.mapper.basedap.IBaseMapperDao;
import org.apache.ibatis.annotations.Param;

import com.chunmi.testcase.model.po.Project;
import com.chunmi.testcase.utils.PageRequest;

public interface ProjectMapper extends IBaseMapperDao<Project,Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_project
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_project
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_project
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_project
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    Project selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_project
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_project
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKey(Project record);

	Integer selectProjectCountsByCondition(@Param("project") Project project);

	List<Project> selectProjectListByCondition(@Param("project")Project project, @Param("pageRequest")PageRequest pageRequest);

	Project selectProjectByName(@Param("projectName")String projectName);

	Integer delProjectById(@Param("id")Long id);
}