package com.chunmi.testcase.mapper;

import java.util.List;

import com.chunmi.testcase.mapper.basedap.IBaseMapperDao;
import org.apache.ibatis.annotations.Param;

import com.chunmi.testcase.model.po.Users;
import com.chunmi.testcase.utils.PageRequest;

public interface UsersMapper extends IBaseMapperDao<Users,Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insertSelective(@Param("user")Users user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    Users selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKey(Users record);


    /**
      * @Description: 根据名字查询用户
      * @Author: sunny
      * @Date: 21:50 2018/11/12
      */
    Users selectUserByName(@Param("userName")String userName);


    /**
      * @Description: 根据条件查询用户数量
      * @Author: sunny
      * @Date: 21:50 2018/11/12
      */
    Integer selectUserCountsByCondition(@Param("user")Users user);


    /**
      * @Description: 根据条件查询用户列表
      * @Author: sunny
      * @Date: 21:50 2018/11/12
      */
    List<Users> selectUserListByCondition(@Param("user")Users user, @Param("pageRequest")PageRequest pageRequest);


    /**
      * @Description:  更新用户状态
      * @Author: sunny
      * @Date: 21:51 2018/11/12
      */
    Integer updateUserStatus(@Param("user")Users user);
}