package com.chunmi.testcase.mapper;

import com.chunmi.testcase.model.po.Users;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    Users selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKey(Users record);
}