package com.chunmi.testcase.mapper;

import java.util.List;

import com.chunmi.testcase.mapper.basedap.IBaseMapperDao;
import org.apache.ibatis.annotations.Param;

import com.chunmi.testcase.model.po.Users;
import com.chunmi.testcase.utils.PageRequest;

public interface UsersMapper extends IBaseMapperDao<Users,Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int insertSelective(@Param("user")Users user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    Users selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Fri Mar 30 15:28:36 CST 2018
     */
    int updateByPrimaryKey(Users record);

    /**
     * 
     * @description: <p class="detail">根据名称查询用户</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2018年4月2日-上午10:58:18
     * @param @param userName
     * @param @return
     * @return Users
     */
	Users selectUserByName(@Param("userName")String userName);

	/**
	 * 
	 * @description: <p class="detail">根据条件查询用户条目数</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2018年4月2日-下午2:50:22
	 * @param @param user
	 * @param @return
	 * @return Integer
	 */
	Integer selectUserCountsByCondition(@Param("user")Users user);

	/**
	 * 
	 * @description: <p class="detail">根据条件查询用户信息</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2018年4月2日-下午2:55:34
	 * @param @param user
	 * @param @param pageRequest
	 * @param @return
	 * @return List<Users>
	 */
	List<Users> selectUserListByCondition(@Param("user")Users user, @Param("pageRequest")PageRequest pageRequest);

	/**
	 * 
	 * @description: <p class="detail">更新用户状态</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2018年4月2日-下午4:27:40
	 * @param @param user
	 * @param @return
	 * @return Integer
	 */
	Integer updateUserStatus(@Param("user")Users user);
}