#设置端口号及上下文路径
server:
  port: 8080
  servlet:
    context-path: /testcase
  
# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://10.0.10.99:3306/test_case_manage?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: chunmi_test
    password: chunmitest
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 800
      min-idle: 50
      initial-size: 200
  
        
#thymeleaf 模板设置
  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html; charset=utf-8
    prefix: classpath:/templates/
    suffix: .html

# 文件上传设置      
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
      
# mybatis配置
mybatis:
  mapper-locations: classpath:com/chunmi/testcase/mapper/*.xml
  type-aliases-package: com.chunmi.testcase.model
  config-location: classpath:/mybatis-config.xml
  
